apiVersion: v1
kind: Service
metadata:
  name: pronunciation-practice-app-api
spec:
  selector:
    app: pronunciation-practice-app-api
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pronunciation-practice-app-api
spec:
  selector:
    matchLabels:
      app: pronunciation-practice-app-api
  replicas: 4
  template:
    metadata:
      labels:
        app: pronunciation-practice-app-api
    spec:
      containers:
      - name: pronunciation-practice-app-api
        image: pronunciation-practice-app-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
